# Generated by Django 6.0 on 2026-01-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_alter_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=20)),
                ('academic_level', models.CharField(choices=[('ENSINO_BASICO', 'Ensino Básico'), ('ENSINO_SECUNDARIO', 'Ensino Secundário'), ('ENSINO_MEDIO', 'Ensino Médio / Técnico Profissional'), ('LICENCIATURA', 'Licenciatura'), ('POS_GRADUACAO', 'Pós-Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORAMENTO', 'Doutoramento')], max_length=100)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(max_length=4, unique=True)),
                ('tax_number', models.CharField(max_length=9, unique=True)),
                ('employee_category', models.CharField(choices=[('Comissário Geral Tributário', 'Comissário Geral Tributário'), ('Comissário Tributário', 'Comissário Tributário'), ('Sub-Comissário Tributário', 'Sub-Comissário Tributário'), ('Superintendente Tributário', 'Superintendente Tributário'), ('Inspector Tributário', 'Inspector Tributário'), ('Sub-Inspector Tributário', 'Sub-Inspector Tributário'), ('Técnico Tributário de 1ª Classe', 'Técnico Tributário de 1ª Classe'), ('Técnico Tributário de 2ª Classe', 'Técnico Tributário de 2ª Classe'), ('Auxiliar Tributário de 1ª Classe', 'Auxiliar Tributário de 1ª Classe'), ('Auxiliar Tributário de 2ª Classe', 'Auxiliar Tributário de 2ª Classe'), ('Auxiliar Tributário de 3ª Classe', 'Auxiliar Tributário de 3ª Classe')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='units.unit')),
            ],
        ),
    ]
