# Generated by Django 6.0 on 2026-01-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
