# Generated by Django 6.0 on 2026-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RLIF', 'Repartição de Logística e Infraestruturas'), ('DPMC', 'Delegação Provincial de Maputo Cidade'), ('UGC', 'Unidades de Grandes Contribuintes'), ('DAF 1', 'Direcção da Área Fiscal do 1º Bairro'), ('DAF 2', 'Direcção da Área Fiscal do 2º Bairro')], max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
